import {
  ConflictException,
  Injectable,
  Logger,
  NotFoundException,
} from '@nestjs/common';
import {
  CredentialKind,
  InstanceStatus,
  PterodactylInstance,
} from '@prisma/client';
import {
  PterodactylApplicationApiClient,
  PterodactylError,
  SsrfValidatorService,
} from '@pterocontrol/pterodactyl-sdk';
import { EventsService } from '../events/events.service';
import { PrismaService } from '../prisma/prisma.service';
import { SecretsService } from '../secrets/secrets.service';
import { CreateInstanceDto } from './dto/create-instance.dto';

/**
 * Instance CRUD, tenant-scoped everywhere: every method takes tenantId
 * as an explicit first argument, sourced by callers exclusively from
 * @CurrentUser() (the JWT), never from a URL param or request body -
 * that's what makes cross-tenant access structurally unreachable here,
 * not just "usually correct."
 */
@Injectable()
export class InstancesService {
  private readonly logger = new Logger(InstancesService.name);

  constructor(
    private readonly prisma: PrismaService,
    private readonly ssrfValidator: SsrfValidatorService,
    private readonly secrets: SecretsService,
    private readonly applicationApi: PterodactylApplicationApiClient,
    private readonly eventsService: EventsService,
  ) {}

  async create(
    tenantId: string,
    dto: CreateInstanceDto,
  ): Promise<PterodactylInstance> {
    await this.ssrfValidator.assertSafe(dto.baseUrl);

    const existing = await this.prisma.pterodactylInstance.findUnique({
      where: { tenantId_baseUrl: { tenantId, baseUrl: dto.baseUrl } },
    });
    if (existing) {
      throw new ConflictException(
        'An instance with this URL already exists for this tenant',
      );
    }

    const instance = await this.prisma.$transaction(async (tx) => {
      const created = await tx.pterodactylInstance.create({
        data: { tenantId, name: dto.name, baseUrl: dto.baseUrl },
      });

      await tx.instanceCredential.create({
        data: {
          instanceId: created.id,
          kind: CredentialKind.APPLICATION_API_KEY,
          // Uint8Array.from(): Prisma's generated Bytes type is
          // Uint8Array<ArrayBuffer>, stricter than Node's own
          // Buffer<ArrayBufferLike> (which technically also allows
          // SharedArrayBuffer-backed instances) - a fresh copy satisfies it.
          ciphertext: Uint8Array.from(this.secrets.encrypt(dto.applicationApiKey)),
        },
      });

      if (dto.clientApiKey) {
        await tx.instanceCredential.create({
          data: {
            instanceId: created.id,
            kind: CredentialKind.CLIENT_API_KEY,
            ciphertext: Uint8Array.from(this.secrets.encrypt(dto.clientApiKey)),
          },
        });
      }

      return created;
    });

    // Connectivity is verified right after creation, but a failure here
    // does not roll back creation - the instance is saved either way,
    // just marked UNREACHABLE with the reason, so the operator can see
    // and fix a bad credential/URL rather than losing the whole submit.
    return this.testAndUpdateStatus(
      instance.id,
      tenantId,
      dto.baseUrl,
      dto.applicationApiKey,
    );
  }

  findAllForTenant(tenantId: string): Promise<PterodactylInstance[]> {
    return this.prisma.pterodactylInstance.findMany({
      where: { tenantId },
      orderBy: { createdAt: 'asc' },
    });
  }

  async findOneForTenant(
    tenantId: string,
    id: string,
  ): Promise<PterodactylInstance> {
    const instance = await this.prisma.pterodactylInstance.findFirst({
      where: { id, tenantId },
    });
    if (!instance) {
      // Same 404 whether the instance doesn't exist at all or belongs to
      // another tenant - never a distinguishing 403, which would leak
      // that the id is valid for *someone*.
      throw new NotFoundException('Instance not found');
    }
    return instance;
  }

  async remove(tenantId: string, id: string): Promise<void> {
    const instance = await this.findOneForTenant(tenantId, id);
    await this.prisma.pterodactylInstance.delete({ where: { id: instance.id } });
  }

  async resync(tenantId: string, id: string): Promise<PterodactylInstance> {
    const instance = await this.findOneForTenant(tenantId, id);
    const credential = await this.prisma.instanceCredential.findUnique({
      where: {
        instanceId_kind: {
          instanceId: instance.id,
          kind: CredentialKind.APPLICATION_API_KEY,
        },
      },
    });
    if (!credential) {
      throw new NotFoundException(
        'Instance has no Application API credential stored',
      );
    }

    const apiKey = this.secrets.decrypt(Buffer.from(credential.ciphertext));
    return this.testAndUpdateStatus(instance.id, tenantId, instance.baseUrl, apiKey);
  }

  private async testAndUpdateStatus(
    instanceId: string,
    tenantId: string,
    baseUrl: string,
    applicationApiKey: string,
  ): Promise<PterodactylInstance> {
    const before = await this.prisma.pterodactylInstance.findUnique({
      where: { id: instanceId },
      select: { status: true },
    });
    const previousStatus = before?.status ?? null;

    let updated: PterodactylInstance;
    try {
      // Re-validated immediately before the actual outbound call, even
      // though create()/resync() already checked it moments earlier -
      // see SsrfValidatorService's doc comment on DNS rebinding.
      await this.ssrfValidator.assertSafe(baseUrl);
      await this.applicationApi.testConnection(baseUrl, applicationApiKey);

      updated = await this.prisma.pterodactylInstance.update({
        where: { id: instanceId },
        data: {
          status: InstanceStatus.ONLINE,
          lastSyncedAt: new Date(),
          lastError: null,
        },
      });
    } catch (error) {
      const message =
        error instanceof PterodactylError || error instanceof Error
          ? error.message
          : String(error);
      this.logger.warn(
        `Instance ${instanceId} (tenant ${tenantId}) connectivity test failed: ${message}`,
      );

      updated = await this.prisma.pterodactylInstance.update({
        where: { id: instanceId },
        data: { status: InstanceStatus.UNREACHABLE, lastError: message },
      });
    }

    if (previousStatus !== null && previousStatus !== updated.status) {
      const occurredAtBucket = Date.now();
      await this.eventsService.record({
        tenantId,
        instanceId,
        type: 'instance_status_changed',
        payload: { from: previousStatus, to: updated.status },
        dedupKey: `instance_status_changed:${instanceId}:${previousStatus}->${updated.status}:${occurredAtBucket}`,
      });
    }

    return updated;
  }
}
